"use client";
import React, { useState, useEffect } from 'react';
import {
    Layers,
    Maximize,
    ZoomIn,
    ZoomOut,
    Map as MapIcon,
    Eye,
    Info,
    Loader2,
    Activity,
    Thermometer,
    Zap,
    X
} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { useLanguage } from '@/hooks/useLanguage';
import { fetchVegetationReports } from '@/lib/api';
import { useSearchParams, useRouter } from 'next/navigation';

export default function MapsPage() {
    const { t } = useLanguage();
    const searchParams = useSearchParams();
    const router = useRouter();
    const [reports, setReports] = useState<any[]>([]);
    const [activeReport, setActiveReport] = useState<any>(null);
    const [loading, setLoading] = useState(true);
    const [activeLayer, setActiveLayer] = useState('ndvi');
    const [hoveredZone, setHoveredZone] = useState<number | null>(null);

    useEffect(() => {
        const load = async () => {
            try {
                const data = await fetchVegetationReports();
                setReports(data);

                const reportId = searchParams.get('report');
                if (reportId) {
                    const found = data.find((r: any) => r._id === reportId);
                    if (found) setActiveReport(found);
                    else setActiveReport(data[0]);
                } else if (data.length > 0) {
                    setActiveReport(data[0]);
                }
            } catch (e) {
                console.error(e);
            } finally {
                setLoading(false);
            }
        };
        load();
    }, [searchParams]);

    const layers = [
        { id: 'ndvi', icon: Activity, label: "NDVI Index", gridKey: 'ndvi' },
        { id: 'gndvi', icon: MapIcon, label: "GNDVI Index", gridKey: 'gndvi' },
        { id: 'savi', icon: Thermometer, label: "SAVI Index", gridKey: 'savi' },
        { id: 'pest', icon: Zap, label: "Pest Risk", gridKey: 'pest' }
    ];

    const [showReportModal, setShowReportModal] = useState(false);

    if (loading) {
        return (
            <div className="h-[60vh] flex items-center justify-center">
                <Loader2 className="w-8 h-8 animate-spin text-primary" />
            </div>
        );
    }

    const currentGrid = activeReport ? activeReport[activeLayer === 'pest' ? 'ndvi' : activeLayer]?.grid : [];
    const currentStats = activeReport ? activeReport[activeLayer === 'pest' ? 'ndvi' : activeLayer]?.stats : null;

    return (
        <div className="h-[calc(100vh-8rem)] flex flex-col gap-6 animate-in fade-in duration-500 relative">

            {/* Report Modal */}
            {showReportModal && activeReport?.detailedReport && (
                <div className="absolute inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-sm p-8 animate-in fade-in duration-200">
                    <div className="bg-[#0f172a] border border-white/10 w-full max-w-4xl h-full max-h-[90vh] rounded-3xl overflow-hidden flex flex-col shadow-2xl relative">
                        {/* Modal Header */}
                        <div className="p-6 border-b border-white/10 flex justify-between items-center bg-[#020617]">
                            <div>
                                <h2 className="text-xl font-bold flex items-center gap-2">
                                    <Activity className="w-5 h-5 text-primary" />
                                    Detailed Analysis Report
                                </h2>
                                <p className="text-sm text-gray-400">Generated by Gemini AI • {new Date(activeReport.processedDate).toLocaleString()}</p>
                            </div>
                            <button
                                onClick={() => setShowReportModal(false)}
                                className="p-2 hover:bg-white/10 rounded-full transition-colors"
                            >
                                <X className="w-6 h-6" />
                            </button>
                        </div>

                        {/* Markdown Content */}
                        <div className="p-8 overflow-y-auto custom-scrollbar flex-1 bg-[#0f172a]">
                            <div className="prose prose-invert prose-lg max-w-none prose-headings:text-primary prose-a:text-blue-400 prose-strong:text-white">
                                <ReactMarkdown remarkPlugins={[remarkGfm]}>
                                    {activeReport.detailedReport}
                                </ReactMarkdown>
                            </div>
                        </div>

                        {/* Footer Actions */}
                        <div className="p-6 border-t border-white/10 bg-[#020617] flex justify-end gap-3">
                            <button
                                onClick={() => setShowReportModal(false)}
                                className="px-6 py-2 rounded-xl bg-white/5 hover:bg-white/10 transition-colors font-bold text-sm"
                            >
                                Close Report
                            </button>
                            <button className="px-6 py-2 rounded-xl bg-primary text-black font-bold text-sm hover:scale-105 transition-transform">
                                Export PDF
                            </button>
                        </div>
                    </div>
                </div>
            )}

            <div className="flex justify-between items-center">
                <div>
                    <h1 className="text-2xl font-bold text-foreground">{t('maps')}</h1>
                    <p className="text-foreground/60 text-sm">
                        {activeReport ? `Analyzing: ${activeReport.originalFile} (${new Date(activeReport.processedDate).toLocaleTimeString()})` : 'Visualize multispectral layers and health indices.'}
                    </p>
                </div>
                <div className="flex gap-4">
                    <select
                        className="bg-muted/50 border border-border/50 rounded-xl px-3 text-sm font-bold outline-none"
                        onChange={(e) => {
                            const r = reports.find(x => x._id === e.target.value);
                            if (r) setActiveReport(r);
                        }}
                        value={activeReport?._id || ''}
                    >
                        {reports.map(r => (
                            <option key={r._id} value={r._id}>{r.originalFile} - {new Date(r.processedDate).toLocaleDateString()}</option>
                        ))}
                    </select>

                    <div className="flex bg-muted/50 p-1 rounded-xl border border-border/50">
                        {layers.map(layer => (
                            <button
                                key={layer.id}
                                onClick={() => setActiveLayer(layer.id)}
                                className={`flex items-center gap-2 px-3 py-1.5 rounded-lg text-xs font-bold transition-all ${activeLayer === layer.id ? 'bg-primary text-black' : 'text-foreground/60 hover:text-foreground'}`}
                            >
                                <layer.icon className="w-3.5 h-3.5" />
                                {layer.label}
                            </button>
                        ))}
                    </div>
                </div>
            </div>

            <div className="flex-1 glass rounded-3xl relative overflow-hidden border border-border/50 group bg-[#020617] shadow-2xl flex">

                {/* Visual Map Area */}
                <div className="relative flex-1 bg-[#0c1311] m-2 rounded-2xl overflow-hidden shadow-inner border border-white/5">
                    {/* Global Spectral Overlay Filter (Subtle ambient) */}
                    <div className={`absolute inset-0 transition-all duration-500 pointer-events-none z-10 ${activeLayer === 'ndvi' ? 'bg-green-500/5' :
                        activeLayer === 'savi' ? 'bg-blue-500/5' :
                            'bg-transparent'
                        }`} />

                    {/* 20x20 Grid Rendering */}
                    <div className="absolute inset-0 grid grid-cols-[repeat(20,minmax(0,1fr))] grid-rows-[repeat(20,minmax(0,1fr))]">
                        {/* Scanning Animation */}
                        <div className="block-scan-overlay" />

                        {(currentGrid && currentGrid.length > 0 ? currentGrid : Array(400).fill(0)).map((val: number, i: number) => {
                            const row = Math.floor(i / 20);
                            const col = i % 20;
                            const zoneValue = val;

                            let spectralFilter = 'bg-transparent';
                            // let borderColor = 'border-white/0'; // Removing border for smoother look

                            // Color Scale Logic
                            if (activeLayer === 'ndvi' || activeLayer === 'gndvi' || activeLayer === 'savi') {
                                if (zoneValue > 0.7) spectralFilter = `bg-green-500 hover:bg-green-400`;
                                else if (zoneValue > 0.5) spectralFilter = `bg-green-500/60 hover:bg-green-500/80`;
                                else if (zoneValue > 0.3) spectralFilter = `bg-yellow-500/60 hover:bg-yellow-500/80`;
                                else if (zoneValue > 0.1) spectralFilter = `bg-orange-500/60 hover:bg-orange-500/80`;
                                else spectralFilter = `bg-red-500/60 hover:bg-red-500/80`;
                            } else if (activeLayer === 'pest') {
                                // Invert logic for pest: low health = high pest risk
                                if (zoneValue < 0.3) spectralFilter = 'bg-red-600/60 animate-pulse';
                                else spectralFilter = 'bg-transparent';
                            }

                            // Ortho Background (Only visible if transparency allows)
                            // We use opacity on the color layer to let the ortho show through
                            // For simplicity in this grid-based view, we'll overlay color with opacity

                            return (
                                <div
                                    key={i}
                                    onMouseEnter={() => setHoveredZone(i)}
                                    // onMouseLeave={() => setHoveredZone(null)} // Keep last hovered for better UX
                                    className={`relative transition-all duration-150 cursor-crosshair group/cell ${activeLayer === 'pest' ? '' : 'hover:scale-125 hover:z-50 hover:shadow-xl hover:ring-1 hover:ring-white/50 rounded-sm'}`}
                                >
                                    {/* Color Overlay */}
                                    <div
                                        className={`absolute inset-0 transition-opacity duration-300 ${spectralFilter}`}
                                        style={{ opacity: activeLayer === 'pest' ? 0.6 : 0.4 }} // Adjust opacity to see underlying "image"
                                    />

                                    {/* Debug/Tooltip on Hover */}
                                    {hoveredZone === i && (
                                        <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-2 glass px-3 py-1.5 rounded-lg border border-white/20 z-[100] whitespace-nowrap pointer-events-none">
                                            <p className="text-[10px] font-bold">Val: {zoneValue.toFixed(3)}</p>
                                        </div>
                                    )}
                                </div>
                            );
                        })}
                    </div>

                    {/* Simulated Ortho Image Background (If real image URL was available, we'd use it here) */}
                    <div
                        className="absolute inset-0 z-0 opacity-30 pointer-events-none"
                        style={{
                            backgroundImage: 'url("/ortho.webp")',
                            backgroundSize: 'cover',
                            backgroundPosition: 'center',
                            filter: 'grayscale(0.5) contrast(1.2)'
                        }}
                    />
                </div>

                {/* Sidebar Details Panel */}
                <div className="w-80 border-l border-white/5 bg-[#050b14] p-6 flex flex-col gap-6 overflow-y-auto custom-scrollbar">

                    <div>
                        <h2 className="text-lg font-black flex items-center gap-2 mb-1">
                            <Activity className="w-5 h-5 text-primary" />
                            {activeLayer.toUpperCase()} Analysis
                        </h2>
                        <p className="text-xs text-muted">Real-time spectral breakdown</p>
                    </div>

                    <div className="glass rounded-2xl p-4 border border-white/5 space-y-3">
                        <div className="flex justify-between items-end">
                            <span className="text-2xl font-black text-white">{currentStats?.mean.toFixed(3) || "0.00"}</span>
                            <span className={`text-xs font-bold px-2 py-1 rounded bg-white/5 ${currentStats?.mean > 0.5 ? 'text-green-400' : 'text-red-400'}`}>
                                {currentStats?.mean > 0.5 ? 'HEALTHY' : 'STRESSED'}
                            </span>
                        </div>
                        <div className="h-1 w-full bg-white/10 rounded-full overflow-hidden">
                            <div className="h-full bg-gradient-to-r from-red-500 via-yellow-500 to-green-500" style={{ width: `${(currentStats?.mean || 0) * 100}%` }} />
                        </div>
                        <div className="flex justify-between text-[10px] text-muted font-mono">
                            <span>Min: {currentStats?.min.toFixed(2)}</span>
                            <span>Max: {currentStats?.max.toFixed(2)}</span>
                        </div>
                    </div>

                    {/* Simple Histogram Visualization */}
                    <div className="glass rounded-2xl p-4 border border-white/5">
                        <h3 className="text-xs font-bold mb-3 uppercase tracking-wider text-muted">Distribution</h3>
                        <div className="flex items-end h-24 gap-1">
                            {/* Create a simple distribution from grid data */}
                            {[0, 0.2, 0.4, 0.6, 0.8].map((range, idx) => {
                                const count = currentGrid?.filter((v: number) => v >= range && v < range + 0.2).length || 0;
                                const maxCount = currentGrid?.length || 1;
                                const height = (count / maxCount) * 100;
                                return (
                                    <div key={idx} className="flex-1 flex flex-col justify-end group/bar">
                                        <div
                                            className="w-full bg-primary/20 border-t border-primary/50 hover:bg-primary transition-all rounded-t-sm relative"
                                            style={{ height: `${Math.max(height * 4, 5)}%` }} // Scaling up for visibility
                                        >
                                            <div className="absolute bottom-full left-1/2 -translate-x-1/2 mb-1 text-[8px] opacity-0 group-hover/bar:opacity-100">{count}</div>
                                        </div>
                                    </div>
                                )
                            })}
                        </div>
                        <div className="flex justify-between text-[8px] text-muted mt-2 border-t border-white/5 pt-1">
                            <span>0.0</span>
                            <span>0.5</span>
                            <span>1.0</span>
                        </div>
                    </div>

                    <div className="glass rounded-2xl p-4 border border-white/5 flex-1">
                        <h3 className="text-xs font-bold mb-3 uppercase tracking-wider text-muted">AI Insights</h3>
                        <div className="space-y-3">
                            <div className="flex items-start gap-3">
                                <div className="w-1.5 h-1.5 rounded-full bg-accent mt-1.5 shrink-0" />
                                <p className="text-xs text-foreground/80 leading-relaxed">
                                    {activeReport?.aiInsights?.summary || "Select a report to view insights."}
                                </p>
                            </div>
                        </div>

                        {activeReport?.detailedReport && (
                            <button
                                onClick={() => setShowReportModal(true)}
                                className="w-full mt-4 py-2 bg-primary/10 text-primary text-xs font-bold rounded-lg hover:bg-primary hover:text-black transition-all border border-primary/20"
                            >
                                View Full Report
                            </button>
                        )}
                    </div>

                </div>

                <div className="absolute left-6 top-1/2 -translate-y-1/2 flex flex-col gap-2 pointer-events-none"> {/* Moved controls to ensure they don't block grid if needed, presently inactive/visual */} </div>

                <div className="absolute bottom-6 left-6 glass p-4 rounded-[1rem] border border-border/50 max-w-sm shadow-2xl z-20 pointer-events-auto">
                    <h3 className="text-[10px] font-bold mb-2 text-foreground flex items-center gap-2 uppercase tracking-widest">
                        Legend
                    </h3>
                    <div className="space-y-1.5">
                        <div className="flex items-center gap-2">
                            <div className="w-8 h-1.5 rounded-sm bg-gradient-to-r from-red-500 via-yellow-500 to-green-500" />
                            <span className="text-[10px] text-muted">NDVI Spectrum</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
